name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.0.0)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Create and activate virtual environment
        run: |
          uv venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          uv pip install -e .[dev]
          uv pip install python-semantic-release build twine

      - name: Update version and changelog
        if: github.event_name == 'workflow_dispatch'
        run: |
          source .venv/bin/activate
          # Update version in pyproject.toml
          sed -i "s/^version = .*/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml
          # Generate changelog
          python -m semantic_release changelog

      - name: Build package
        run: |
          source .venv/bin/activate
          python -m build

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          source .venv/bin/activate
          twine upload dist/*

      - name: Commit version changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          source .venv/bin/activate
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml CHANGELOG.md
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push
