name: Security

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Create and activate virtual environment
        run: |
          uv venv
          source .venv/bin/activate
          which python
          python --version
          pip list

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run safety checks
        run: |
          source .venv/bin/activate
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            python -m safety scan --full-report --base-ref=${{ github.base_ref }} --head-ref=${{ github.head_ref }}
          else
            python -m safety scan --full-report
          fi

      - name: Run bandit checks
        run: |
          source .venv/bin/activate
          python -m bandit -r yaml2pydantic

      - name: Run dependency review
        uses: actions/dependency-review-action@v3
